"""course, tee set, hole

Revision ID: 4f26b98d80a9
Revises: f9504e5910ec
Create Date: 2026-08-24 15:35:28.473520

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f26b98d80a9'
down_revision = 'f9504e5910ec'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('club_name', sa.String(length=128), nullable=False),
    sa.Column('course_name', sa.String(length=128), nullable=False),
    sa.Column('address', sa.String(length=255), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('state', sa.String(length=64), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('scorecard_url', sa.String(length=255), nullable=True),
    sa.Column('external_source', sa.String(length=32), nullable=True),
    sa.Column('external_id', sa.String(length=8), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_source', 'external_id', name='uq_course_external')
    )
    op.create_table('tee_set',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False),
    sa.Column('color', sa.String(length=32), nullable=True),
    sa.Column('gender', sa.String(length=1), nullable=False),
    sa.Column('par', sa.Integer(), nullable=True),
    sa.Column('course_rating', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('slope_rating', sa.Integer(), nullable=True),
    sa.Column('yardage', sa.Integer(), nullable=True),
    sa.Column('meters', sa.Integer(), nullable=True),
    sa.Column('hole_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tee_set', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tee_set_course_id'), ['course_id'], unique=False)

    op.create_table('hole',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tee_set_id', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('par', sa.Integer(), nullable=False),
    sa.Column('stroke_index', sa.Integer(), nullable=False),
    sa.Column('yardage', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['tee_set_id'], ['tee_set.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tee_set_id', 'number', name='uq_hole_tee_set_number')
    )
    with op.batch_alter_table('hole', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hole_tee_set_id'), ['tee_set_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hole', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hole_tee_set_id'))

    op.drop_table('hole')
    with op.batch_alter_table('tee_set', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tee_set_course_id'))

    op.drop_table('tee_set')
    op.drop_table('course')
    # ### end Alembic commands ###
