"""round and hole_score

Revision ID: adc7f7e11af8
Revises: 4f26b98d80a9
Create Date: 2026-08-24 15:50:29.575168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adc7f7e11af8'
down_revision = '4f26b98d80a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('round',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('tee_set_id', sa.Integer(), nullable=False),
    sa.Column('played_date', sa.Date(), nullable=False),
    sa.Column('notes', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('gross_score', sa.Integer(), nullable=True),
    sa.Column('adjusted_gross_score', sa.Integer(), nullable=True),
    sa.Column('score_differential', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['course.id'], ),
    sa.ForeignKeyConstraint(['tee_set_id'], ['tee_set.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('round', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_round_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_round_tee_set_id'), ['tee_set_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_round_user_id'), ['user_id'], unique=False)

    op.create_table('hole_score',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('round_id', sa.Integer(), nullable=False),
    sa.Column('hole_id', sa.Integer(), nullable=False),
    sa.Column('strokes', sa.Integer(), nullable=False),
    sa.Column('putts', sa.Integer(), nullable=True),
    sa.Column('fairway_hit', sa.Boolean(), nullable=True),
    sa.Column('gir', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['hole_id'], ['hole.id'], ),
    sa.ForeignKeyConstraint(['round_id'], ['round.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('round_id', 'hole_id', name='uq_hole_score_round_hole')
    )
    with op.batch_alter_table('hole_score', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_hole_score_hole_id'), ['hole_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_hole_score_round_id'), ['round_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hole_score', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_hole_score_round_id'))
        batch_op.drop_index(batch_op.f('ix_hole_score_hole_id'))

    op.drop_table('hole_score')
    with op.batch_alter_table('round', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_round_user_id'))
        batch_op.drop_index(batch_op.f('ix_round_tee_set_id'))
        batch_op.drop_index(batch_op.f('ix_round_course_id'))

    op.drop_table('round')
    # ### end Alembic commands ###
